### ISSUE TITLE
Criteria to bumb version

### ISSUE THREAD

**Issue by 7Ds7** [PolymerElements/iron-elements#23]
Hello all,

I was wondering what is the criteria to bump the version of the iron-polymer elements, or any other '*-elements' for that matter.

The main problem is to know what is the best way to the updates to all the Polymer components, as of now in my bower dependencies i have `"iron-elements": "PolymerElements/iron-elements#~1.0.3"`

In this specific case iron-ajax is not up to date with the version 1.0.4 that fixes a major formData issue.
From what i understand iron-ajax#1.0.0 is a dependency for google-chart#1.0.2.

Does this mean that the version is bumped when all the Polymer have the requirements for the dependencies met?

What is the best way to get all the Polymer elements up to date and still use PolymerElements/iron-elements ?

**Comment by tjsavage** [comment]
Generally this `iron-elements` repo and other meta-repos like PolymerElements/paper-elements are meant to represent major version sets of the elements, to be used primarily as meta-data for things like the [element catalog](https://elements.polymer-project.org). Because this repo has all dependencies as `^1.0.0` bower will try to get the highest 1.\* version of the element, unless a lower version is required in another dependency.

In the case you mention with google-chart and iron-ajax, google-chart depending on `#1.0.0` was a bug in the bower.json of google-chart - it is fixed now: https://github.com/GoogleWebComponents/google-chart/commit/6560a673809adf0a50bf388ad064d569d56b61f3

In general, these meta-repos are not ideal to use as a bower dependency - I'd highly recommend just using the individual element repos that you depend on in your app rather than this.
